#!/bin/bash

# This shell patches the parser.py module generated by the kaitai-struct-compiler
# This address the issue where enums imported from another module do not have
# the module name before the class name
# e.g PrimaryHeader.Type instead of primary_header.PrimaryHeader.Type
# Git issue tracking this bug: https://github.com/kaitai-io/kaitai_struct/issues/703

sed -i 's/PrimaryHeader.Type/primary_header.PrimaryHeader.Type/g' ./led_cube_data/parser/parser.py
